// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD1JAJEd8Um7z6XP7cNd9JmaXGsHaqehI',
    appId: '1:347819806364:web:7587d60dfab149f3fba759',
    messagingSenderId: '347819806364',
    projectId: 'testing-23280',
    authDomain: 'testing-23280.firebaseapp.com',
    databaseURL: 'https://testing-23280-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'testing-23280.firebasestorage.app',
    measurementId: 'G-R8QT7YMYQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7O6Oknhy4ZmbeCg2FXI-CnpImfAEvF5g',
    appId: '1:347819806364:android:53f045421ecbd73bfba759',
    messagingSenderId: '347819806364',
    projectId: 'testing-23280',
    databaseURL: 'https://testing-23280-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'testing-23280.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm1U8uIS4MB7WQHehlWGe5E3ps8As2Dno',
    appId: '1:347819806364:ios:605288ea3234754dfba759',
    messagingSenderId: '347819806364',
    projectId: 'testing-23280',
    databaseURL: 'https://testing-23280-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'testing-23280.firebasestorage.app',
    iosBundleId: 'com.example.health',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm1U8uIS4MB7WQHehlWGe5E3ps8As2Dno',
    appId: '1:347819806364:ios:605288ea3234754dfba759',
    messagingSenderId: '347819806364',
    projectId: 'testing-23280',
    databaseURL: 'https://testing-23280-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'testing-23280.firebasestorage.app',
    iosBundleId: 'com.example.health',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCD1JAJEd8Um7z6XP7cNd9JmaXGsHaqehI',
    appId: '1:347819806364:web:3444c7f692211539fba759',
    messagingSenderId: '347819806364',
    projectId: 'testing-23280',
    authDomain: 'testing-23280.firebaseapp.com',
    databaseURL: 'https://testing-23280-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'testing-23280.firebasestorage.app',
    measurementId: 'G-Q3HLYW0DZB',
  );

}